version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq_go_net

  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - rabbitmq_go_net

  flask:
    build:
      context: ./api
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
    networks:
      - rabbitmq_go_net

  # consumer:
  #   build:
  #     context: ./consumer
  #     dockerfile: Dockerfile.consumer    # Update Dockerfile filename
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - rabbitmq_go_net

  # publisher:
  #   build:
  #     context: ./publisher
  #     dockerfile: Dockerfile.publisher   # Update Dockerfile filename
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge