FROM ubuntu

WORKDIR /app

RUN \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get -y install python3 python3-dev python3-pip python3-wheel

RUN pip install --upgrade pip
RUN pip install pika==1.3.2

COPY publisher.py .

#CMD ["python3", "publisher.py"]
